// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh396l-cvaTWjGoadCKUhQHz9GFOJWXjM',
    appId: '1:485973736243:web:0c23e409a93f63f3f75c46',
    messagingSenderId: '485973736243',
    projectId: 'mostadam-cec2d',
    authDomain: 'mostadam-cec2d.firebaseapp.com',
    storageBucket: 'mostadam-cec2d.firebasestorage.app',
    measurementId: 'G-481T4M582L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmjO3b25R_Jms0oPXp-MjBw5lEruyEUk',
    appId: '1:485973736243:android:78006695139b6a9af75c46',
    messagingSenderId: '485973736243',
    projectId: 'mostadam-cec2d',
    storageBucket: 'mostadam-cec2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxzhGL1nnbiskg7SfD68XwfmgXSFITR_w',
    appId: '1:485973736243:ios:08dcd3d769906915f75c46',
    messagingSenderId: '485973736243',
    projectId: 'mostadam-cec2d',
    storageBucket: 'mostadam-cec2d.firebasestorage.app',
    iosBundleId: 'com.example.mostadam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxzhGL1nnbiskg7SfD68XwfmgXSFITR_w',
    appId: '1:485973736243:ios:08dcd3d769906915f75c46',
    messagingSenderId: '485973736243',
    projectId: 'mostadam-cec2d',
    storageBucket: 'mostadam-cec2d.firebasestorage.app',
    iosBundleId: 'com.example.mostadam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh396l-cvaTWjGoadCKUhQHz9GFOJWXjM',
    appId: '1:485973736243:web:c2f2c6330889556cf75c46',
    messagingSenderId: '485973736243',
    projectId: 'mostadam-cec2d',
    authDomain: 'mostadam-cec2d.firebaseapp.com',
    storageBucket: 'mostadam-cec2d.firebasestorage.app',
    measurementId: 'G-CEFP9KV4Y5',
  );
}
